version: '3.8'

services:
  exam-display:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sta-exams-display
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - exam-network

networks:
  exam-network:
    driver: bridge
